language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
notifications:
  slack:
    secure: Q55PbGy8fdsRU4uW03UHTbYVVCzQdEacLJ2lP3tpfucIJkJaGO56faHAaB/oNJS4WuqC1/DO1o73P0E77XVM/36nTG0xF9glm8qnk1WGmdeVx3fnMW3mCH0pGJQaCFeHGOQb1Gfj5wonW0tMYmFzArUSQ/BEPDeqO8mn098N9/McywM8FS/QqtcutjbZipOjrxhwcG4Z571ukSSbOdlL/7o/oEZOcRvFNEt4PXNp6iSqNKWIs2xNPXKuxRtRHdH5HRZP7LAqe89hDgsLVVzBbbFwo33pDnH3nBa86P4csHglYT5t4xV/wCMqoKUv0RZORUQRVx1TTkHAcIIYKgDalxlPxpqIU34SFfSzBhvsVxT/rpQBk84STycJFXBA3MBLNCnMaXUlNknLQf6THHl//b2TyoKAUaiJUXw15rHAo+YUjsVGf5Z9S4J5DroYbOkSR7KILtKxccnyGvST0h2rerDU97BHQlJAZv0rkVXqOsfVqlCIqaEVoRikOePD3YAleKsJcuT/CZmuL9tscviGuAducfIbcvy45fauR5raOMeOyHnEGPjgfz90FFKkkUMb4INWcPBmZON1XJEnOCjhuTBUNcb/yL2OA5+JbZpS8inTRZ4Z1M6kYp8xA+clkQ8qo02hkMoCYKL6ekVEvBdr1G46Kax1DYaFIna2sdI6SzY=
