language: node_js
node_js:
    - '7'
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'

jobs:
    include:
        - stage: npm release
          if: tag IS present
          node_js: 12
          deploy:
              provider: npm
              email: rogier+npm@konfirm.eu
              on:
                  branch: master
                  tags: true
              api_key:
                  secure: Cjaq+DvSb06VvilY9VUm+Zlv+KXERygYFVL0gfTejMcjmhtqrEqF2YgSZp6I3zkcfEB+rDPNYG6Jw2+pXk7BpxXVeHcTd5HnCf31WP68syzPXtEinyfVlfw+HI78OKVuq82dRIZzQc2eyMHJQtVB9noTO7QJ+vhmhTFe/2E60rSeldSYESP5Y+k6uRQW3BinCJnEB1xeIZnIuD3q8L64lnKKhpXpsnuMtaMcRTUAlEwOGunzWF8s8yWcnpHn32sU4coc9EcqG1vjTMZuVaNuw0d9DkrAnTUXcE2ztvMUkuvP0tplNiv3pQteK2/kx1KU+f7a6Y1CXsVRw7+QdyIFb+j1JLxj7owoqVE0F88gq9GMa8QWqM4qicBGcKRF/eYEkRek1Girw6pFjNQYunvOPhSigr8HZSHqHTQclLO63BPeZVBqmhKc5mwJJ3ETHUpyRNfBsUYaFFWzjMYdV1/tavBlUgKQ7IfUONaR5aK80op3YxMj1/nQ225QxITkb0JxEvAWBya0FJJPEzIbYEZwC6zcTk55W/CpmAy0kbOsORMZVgN4LKu+k73uXWe3NP4gV/OCzFSK7Tk3aTa6boze+2wdhOm2GEP8aObmsjDIwmKc8UL90UUU2bDFWQMbeDke2NIGjtFHEmD6abRExnh4iAhRlS0bty0CJu+W0rJZzHY=

notifications:
    slack:
        secure: Q55PbGy8fdsRU4uW03UHTbYVVCzQdEacLJ2lP3tpfucIJkJaGO56faHAaB/oNJS4WuqC1/DO1o73P0E77XVM/36nTG0xF9glm8qnk1WGmdeVx3fnMW3mCH0pGJQaCFeHGOQb1Gfj5wonW0tMYmFzArUSQ/BEPDeqO8mn098N9/McywM8FS/QqtcutjbZipOjrxhwcG4Z571ukSSbOdlL/7o/oEZOcRvFNEt4PXNp6iSqNKWIs2xNPXKuxRtRHdH5HRZP7LAqe89hDgsLVVzBbbFwo33pDnH3nBa86P4csHglYT5t4xV/wCMqoKUv0RZORUQRVx1TTkHAcIIYKgDalxlPxpqIU34SFfSzBhvsVxT/rpQBk84STycJFXBA3MBLNCnMaXUlNknLQf6THHl//b2TyoKAUaiJUXw15rHAo+YUjsVGf5Z9S4J5DroYbOkSR7KILtKxccnyGvST0h2rerDU97BHQlJAZv0rkVXqOsfVqlCIqaEVoRikOePD3YAleKsJcuT/CZmuL9tscviGuAducfIbcvy45fauR5raOMeOyHnEGPjgfz90FFKkkUMb4INWcPBmZON1XJEnOCjhuTBUNcb/yL2OA5+JbZpS8inTRZ4Z1M6kYp8xA+clkQ8qo02hkMoCYKL6ekVEvBdr1G46Kax1DYaFIna2sdI6SzY=
